### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-3-evaluacion-intermedia-PatriMalvido#1]
Buen trabajo @PatriMalvido  !

### Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Si utilizas SASS, recuerda instalarlo y grabarlo en el `package.json` con `npm install --save node-sass`
- [x] Tu proyecto no se ve correctamente en Github Pags porque falta una línea con `"homepage": "./",` en tu `package.json`.
- [x] Aquí <https://github.com/Adalab/modulo-3-evaluacion-intermedia-PatriMalvido/blob/fef18e39949b2830d9e5101285dce343c1caef89/src/components/App.js#L31> no debes usar `setStudent()` sino `setNewStudent()`
- [x] Revisa los metadatos en `index.html` (`lang`, `title`...)
- [x] Limpia e indenta el código
- [x] Haz los bonus del ejercicio para que sigas practicando! 

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by PatriMalvido** [comment]
Hola Iván, gracias por los comentarios. 
Tengo una duda en uno de ellos, en los metadatos, me imagino que será que no he cambiado el title, dejé por defecto el de la plantilla. Ya lo he cambiado, pero si es que te refieres a otra cosa por favor me comentas.
Muchas gracias!

**Comment by igarrido-adalab** [comment]
Exacto, al `<title>` solamente. Ahora está genial!

**Comment by igarrido-adalab** [comment]
Está perfecto!
